# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tesiLaureaEmoticron' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tesiLaureaEmoticron
  pod 'GoogleMobileVision'	, '1.1.0'

  target 'tesiLaureaEmoticronTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tesiLaureaEmoticronUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
